"""add audit fields

Revision ID: ad4a02af2953
Revises: f20b2e6e7788
Create Date: 2026-04-07 08:44:25.390387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4a02af2953'
down_revision: Union[str, Sequence[str], None] = 'f20b2e6e7788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('clients', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['created_by_id'], ['id'])
    op.add_column('machine_configs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('machine_configs', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('machine_configs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machine_configs', 'users', ['created_by_id'], ['id'])
    op.add_column('materials', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('materials', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'materials', 'users', ['created_by_id'], ['id'])
    op.add_column('pieces', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('pieces', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pieces', 'users', ['created_by_id'], ['id'])
    op.add_column('quotation_items', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotation_items', 'users', ['created_by_id'], ['id'])
    op.add_column('quotations', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotations', 'users', ['created_by_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'created_by_id')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.drop_column('quotation_items', 'created_by_id')
    op.drop_constraint(None, 'pieces', type_='foreignkey')
    op.drop_column('pieces', 'created_by_id')
    op.drop_column('pieces', 'updated_at')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'created_by_id')
    op.drop_column('materials', 'updated_at')
    op.drop_constraint(None, 'machine_configs', type_='foreignkey')
    op.drop_column('machine_configs', 'created_by_id')
    op.drop_column('machine_configs', 'updated_at')
    op.drop_column('machine_configs', 'created_at')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'created_by_id')
    op.drop_column('clients', 'updated_at')
    # ### end Alembic commands ###
