"""initial schema

Revision ID: f20b2e6e7788
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 08:41:01.697590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20b2e6e7788'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_config', sa.Column('logo_data', sa.LargeBinary(), nullable=True))
    op.add_column('company_config', sa.Column('logo_filename', sa.String(), nullable=True))
    op.drop_column('company_config', 'logo_path')
    op.add_column('pieces', sa.Column('dxf_data', sa.LargeBinary(), nullable=True))
    op.add_column('pieces', sa.Column('dxf_filename', sa.String(), nullable=True))
    op.add_column('pieces', sa.Column('preview_data', sa.LargeBinary(), nullable=True))
    op.drop_column('pieces', 'dxf_path')
    op.drop_column('pieces', 'preview_path')
    op.add_column('quotations', sa.Column('pdf_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotations', 'pdf_data')
    op.add_column('pieces', sa.Column('preview_path', sa.VARCHAR(), nullable=True))
    op.add_column('pieces', sa.Column('dxf_path', sa.VARCHAR(), nullable=True))
    op.drop_column('pieces', 'preview_data')
    op.drop_column('pieces', 'dxf_filename')
    op.drop_column('pieces', 'dxf_data')
    op.add_column('company_config', sa.Column('logo_path', sa.VARCHAR(), nullable=True))
    op.drop_column('company_config', 'logo_filename')
    op.drop_column('company_config', 'logo_data')
    # ### end Alembic commands ###
